---
- name: Converge
  #hosts: all
  hosts: management1
  vars:
#    management_networks_naming: "ice"
    j2_node_main_network: ice1-1
    j2_current_iceberg_network: ice1
#    j2_node_main_network_interface: en0
#    j2_management_networks:
#      - ice1-1


  tasks:
    - name: "Include dhcp_server"
      include_role:
        name: "dhcp_server"
